[2024-05-01T16:00:06.319+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T16:00:00.625445+00:00 [queued]>
[2024-05-01T16:00:06.343+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T16:00:00.625445+00:00 [queued]>
[2024-05-01T16:00:06.344+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2024-05-01T16:00:06.379+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): fetch_dataset> on 2024-05-01 16:00:00.625445+00:00
[2024-05-01T16:00:06.395+0000] {standard_task_runner.py:57} INFO - Started process 461 to run task
[2024-05-01T16:00:06.409+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'diabetes_prediction', 'fetch_dataset', 'manual__2024-05-01T16:00:00.625445+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag1.py', '--cfg-path', '/tmp/tmpgwgs45m6']
[2024-05-01T16:00:06.413+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask fetch_dataset
[2024-05-01T16:00:06.560+0000] {task_command.py:410} INFO - Running <TaskInstance: diabetes_prediction.fetch_dataset manual__2024-05-01T16:00:00.625445+00:00 [running]> on host c90068845469
[2024-05-01T16:00:06.861+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_prediction' AIRFLOW_CTX_TASK_ID='fetch_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T16:00:00.625445+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T16:00:00.625445+00:00'
[2024-05-01T16:00:08.648+0000] {warnings.py:110} WARNING - /opt/***/dags/dag1.py:15: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  data = fetch_ucirepo(id=296)

[2024-05-01T16:00:10.358+0000] {xcom.py:640} ERROR - Object of type Index is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-01T16:00:10.364+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.indexes.base.Index'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag1.py", line 17, in fetch_dataset
    kwargs['ti'].xcom_push(key='dataframe', value=data)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2384, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 243, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Index is not JSON serializable
[2024-05-01T16:00:10.393+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_prediction, task_id=fetch_dataset, execution_date=20240501T160000, start_date=20240501T160006, end_date=20240501T160010
[2024-05-01T16:00:10.431+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 29 for task fetch_dataset (Object of type Index is not JSON serializable; 461)
[2024-05-01T16:00:10.481+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-05-01T16:00:10.553+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
